// MARK: - Clodey sprite data

/// All sprite frames for Clodey the blob.
/// Each frame is a grid of SpriteColor codes.
/// Grid size: 12×12 pixels.
enum ClodeySprites {

    // ── Idle frames (gentle breathing) ──────────────────────────────

    static let idle1: [[SpriteColor]] = parseSprite("""
....BBBB....
...BBBBBB...
..BBBBBBBB..
..BBEBBEBB..
..BBBBBBBB..
..BCBBBBCB..
..BBBBBBBB..
...BBBBBB...
....BBBB....
............
............
............
""")

    static let idle2: [[SpriteColor]] = parseSprite("""
............
....BBBB....
...BBBBBB...
..BBBBBBBB..
..BBEBBEBB..
..BBBBBBBB..
..BCBBBBCB..
..BBBBBBBB..
...BBBBBB...
....BBBB....
............
............
""")

    // ── Happy frames (little bounce) ────────────────────────────────

    static let happy1: [[SpriteColor]] = parseSprite("""
.S..BBBB..S.
...BBBBBB...
..BBBBBBBB..
..BBEBBEBB..
..BBBBBBBB..
..BCBMMBCB..
..BBBBBBBB..
...BBBBBB...
....BBBB....
............
............
............
""")

    static let happy2: [[SpriteColor]] = parseSprite("""
............
.S..BBBB..S.
...BBBBBB...
..BBBBBBBB..
..BBEBBEBB..
..BBBBBBBB..
..BCBMMBCB..
..BBBBBBBB..
...BBBBBB...
....BBBB....
............
............
""")

    static let happy3: [[SpriteColor]] = parseSprite("""
S...BBBB...S
...BBBBBB...
..BBBBBBBB..
..BBEBBEBB..
..BBBBBBBB..
..BCBMMBCB..
..BBBBBBBB..
...BBBBBB...
....BBBB....
............
............
............
""")

    // ── Tired frames (droopy, slow sway) ────────────────────────────

    static let tired1: [[SpriteColor]] = parseSprite("""
............
............
....BBBB....
...BBBBBB...
..BBBBBBBB..
..BBEBBEBB..
..BBBBBBBB..
..BBBBBBBB..
...BBBBBB...
....BBBB....
............
............
""")

    static let tired2: [[SpriteColor]] = parseSprite("""
............
............
....BBBB....
...BBBBBB...
..BBBBBBBB..
..BDEBBDEB..
..BBBBBBBB..
..BBBBBBBB..
...BBBBBB...
....BBBB....
............
............
""")

    // ── Sleeping frames (ZZZ bubbles) ───────────────────────────────

    static let sleeping1: [[SpriteColor]] = parseSprite("""
..........Z.
.........Z..
....BBBB....
...BBBBBB...
..BBBBBBBB..
..BBDBBDBB..
..BBBBBBBB..
..BBBBBBBB..
...BBBBBB...
....BBBB....
............
............
""")

    static let sleeping2: [[SpriteColor]] = parseSprite("""
.........Z..
..........Z.
....BBBB....
...BBBBBB...
..BBBBBBBB..
..BBDBBDBB..
..BBBBBBBB..
..BBBBBBBB..
...BBBBBB...
....BBBB....
............
............
""")

    // ── Excited frames (jumping with arms up) ───────────────────────

    static let excited1: [[SpriteColor]] = parseSprite("""
.S..BBBB..S.
...BBBBBB...
..BBBBBBBB..
..BBEBBEBB..
..BBBBBBBB..
..BCBMMBCB..
..BBBBBBBB..
...BBBBBB...
....BBBB....
............
............
............
""")

    static let excited2: [[SpriteColor]] = parseSprite("""
............
............
.S..BBBB..S.
...BBBBBB...
..BBBBBBBB..
..BBEBBEBB..
..BBBBBBBB..
..BCBMMBCB..
..BBBBBBBB..
...BBBBBB...
....BBBB....
............
""")

    static let excited3: [[SpriteColor]] = parseSprite("""
S..........S
.S..BBBB..S.
...BBBBBB...
..BBBBBBBB..
..BBEBBEBB..
..BBBBBBBB..
..BCBMMBCB..
..BBBBBBBB..
...BBBBBB...
....BBBB....
............
............
""")

    // ── Critical frames (melting/deflating) ─────────────────────────

    static let critical1: [[SpriteColor]] = parseSprite("""
............
............
............
....BBBB....
...BBBBBB...
..BBEBBEBB..
..BBBBBBBB..
..BBBBBBBB..
..BBBBBBBB..
...BBBBBB...
..BBBBBBBB..
............
""")

    static let critical2: [[SpriteColor]] = parseSprite("""
............
............
............
............
....BBBB....
...BBEBBEB..
..BBBBBBBB..
..BBBBBBBB..
..BBBBBBBB..
..BBBBBBBB..
.BBBBBBBBBB.
............
""")

    // ── Reborn frames (explosion of energy) ─────────────────────────

    static let reborn1: [[SpriteColor]] = parseSprite("""
S...BBBB...S
...BBBBBB...
..BBBBBBBB..
..BBEBBEBB..
..BBBBBBBB..
..BCBMMBCB..
..BBBBBBBB..
...BBBBBB...
....BBBB....
............
............
............
""")

    static let reborn2: [[SpriteColor]] = parseSprite("""
.S.S.SS.S.S.
S...BBBB...S
...BBBBBB...
..BBBBBBBB..
..BBEBBEBB..
..BBBBBBBB..
..BCBMMBCB..
..BBBBBBBB..
...BBBBBB...
....BBBB....
............
............
""")

    static let reborn3: [[SpriteColor]] = parseSprite("""
S.S.S..S.S.S
.S.S.SS.S.S.
S...BBBB...S
...BBBBBB...
..BBBBBBBB..
..BBEBBEBB..
..BBBBBBBB..
..BCBMMBCB..
..BBBBBBBB..
...BBBBBB...
....BBBB....
............
""")

    // ── Peeking frames (hiding behind notch) ────────────────────────

    static let peeking1: [[SpriteColor]] = parseSprite("""
............
............
............
............
............
............
............
............
....BBBB....
...BBBBBB...
..BBEBBEBB..
..BBBBBBBB..
""")

    static let peeking2: [[SpriteColor]] = parseSprite("""
............
............
............
............
............
............
....BBBB....
...BBBBBB...
..BBBBBBBB..
..BBEBBEBB..
..BBBBBBBB..
..BBBBBBBB..
""")

    // ── Movement poses (single-frame overrides during animations) ──

    /// Falling: surprised wide eyes, body shifted up as if arms are raised
    static let falling1: [[SpriteColor]] = parseSprite("""
..WWBBBBWW..
...BBBBBB...
..BBBBBBBB..
..BWEBBEWB..
..BBBBBBBB..
..BBMBBMBB..
..BBBBBBBB..
...BBBBBB...
....BBBB....
............
............
............
""")

    /// Squash: flat wide blob, compressed on landing
    static let squash1: [[SpriteColor]] = parseSprite("""
............
............
............
............
............
............
..BBBBBBBB..
.BBBBBBBBBB.
.BBEBBBBEBB.
.BBCBBBBCBB.
.BBBBBBBBBB.
............
""")

    /// Lean left: body shifted and stretched left
    static let leanLeft1: [[SpriteColor]] = parseSprite("""
...BBBB.....
..BBBBBB....
.BBBBBBBB...
.BBEBBEBB...
.BBBBBBBB...
.BCBBBBCB...
.BBBBBBBB...
..BBBBBB....
...BBBB.....
............
............
............
""")

    /// Lean right: body shifted and stretched right
    static let leanRight1: [[SpriteColor]] = parseSprite("""
.....BBBB...
....BBBBBB..
...BBBBBBBB.
...BBEBBEBB.
...BBBBBBBB.
...BCBBBBCB.
...BBBBBBBB.
....BBBBBB..
.....BBBB...
............
............
............
""")

    // ── Coding frames (fetch laptop → type → hide) ──────────────────

    // Phase 1: reach/fetch
    static let coding1: [[SpriteColor]] = parseSprite("""
....BBBB....
...BBBBBB...
..BBBBBBBB..
..BBEBBEBB..
..BBBBBBBB..
..BCBBBBCB..
..BBBBBBBB..
...BBBBBBD..
....BBBBD...
.........DD.
............
............
""")

    static let coding2: [[SpriteColor]] = parseSprite("""
....BBBB....
...BBBBBB...
..BBBBBBBB..
..BBEBBEBB..
..BBBBBBBB..
..BCBBBBCB..
..BBBBBBBB..
...BBBBBB...
....BBBB....
.DDDDDDDDDD.
.DDDDDDDDDD.
.DAAAAAAAAD.
""")

    // Phase 2: typing (focused eyes, screen animation)
    static let coding3: [[SpriteColor]] = parseSprite("""
....BBBB....
...BBBBBB...
..BBBBBBBB..
..BBDBBDBB..
..BBBBBBBB..
..BBBBBBBB..
..BBBBBBBB..
...BBBBBB...
....BBBB....
.DDDDDDDDDD.
.DGGGGGGGGD.
.DAAAAAAAAD.
""")

    static let coding4: [[SpriteColor]] = parseSprite("""
....BBBB....
...BBBBBB...
..BBBBBBBB..
..BBDBBDBB..
..BBBBBBBB..
..BBBBBBBB..
..BBBBBBBB..
...BBBBBB...
....BBBB....
.DDDDDDDDDD.
.DGLGGGGGGD.
.DAADAAADAD.
""")

    static let coding5: [[SpriteColor]] = parseSprite("""
....BBBB....
...BBBBBB...
..BBBBBBBB..
..BBDBBDBB..
..BBBBBBBB..
..BBBBBBBB..
..BBBBBBBB..
...BBBBBB...
....BBBB....
.DDDDDDDDDD.
.DGGGGGLGGD.
.DADADAADAD.
""")

    static let coding6: [[SpriteColor]] = parseSprite("""
....BBBB....
...BBBBBB...
..BBBBBBBB..
..BBDBBDBB..
..BBBBBBBB..
..BBBBBBBB..
..BBBBBBBB..
...BBBBBB...
....BBBB....
.DDDDDDDDDD.
.DGGGGGGGLD.
.DAADAAADAD.
""")

    // Phase 3: close/hide
    static let coding7: [[SpriteColor]] = parseSprite("""
....BBBB....
...BBBBBB...
..BBBBBBBB..
..BBEBBEBB..
..BBBBBBBB..
..BCBBBBCB..
..BBBBBBBB..
...BBBBBB...
....BBBB....
.DDDDDDDDDD.
.DDDDDDDDDD.
.DAAAAAAAAD.
""")

    static let coding8: [[SpriteColor]] = parseSprite("""
....BBBB....
...BBBBBB...
..BBBBBBBB..
..BBEBBEBB..
..BBBBBBBB..
..BCBBBBCB..
..BBBBBBBB..
...BBBBBB...
....BBBB....
............
............
............
""")

    // ── Debugging frames (magnifier → squint → "!" discovery) ───────

    static let debug1: [[SpriteColor]] = parseSprite("""
....BBBB.DD.
...BBBBBBDGD
..BBBBBBBBDD
..BBEBBEBB..
..BBBBBBBB..
..BCBBBBCB..
..BBBBBBBB..
...BBBBBB...
....BBBB....
............
............
............
""")

    static let debug2: [[SpriteColor]] = parseSprite("""
....BBBB.DD.
...BBBBBBDGD
..BBBBBBBBDD
..BBDBBDBB..
..BBBBBBBB..
..BBBBBBBB..
..BBBBBBBB..
...BBBBBB...
....BBBB....
............
............
............
""")

    static let debug3: [[SpriteColor]] = parseSprite("""
....BBBB....
...BBBBBBDD.
..BBBBBBBDGD
..BBDBBDBBDD
..BBBBBBBB..
..BBBBBBBB..
..BBBBBBBB..
...BBBBBB...
....BBBB....
............
............
............
""")

    static let debug4: [[SpriteColor]] = parseSprite("""
....BBBBS...
...BBBBBB.S.
..BBBBBBBBSS
..BBDBBDBB..
..BBBBBBBB..
..BBBBBBBB..
..BBBBBBBB..
...BBBBBB...
....BBBB....
............
............
............
""")

    static let debug5: [[SpriteColor]] = parseSprite("""
....BBBB....
...BBBBBB...
..BBBBBBBB..
..BBEBBEBB..
..BBBBBBBB..
..BCBBBBCB..
..BBBBBBBB..
...BBBBBB...
....BBBB....
............
............
............
""")

    // ── Compiling frames (progress bar filling) ──────────────────────

    static let compile1: [[SpriteColor]] = parseSprite("""
....BBBB....
...BBBBBB...
..BBBBBBBB..
..BBEBBEBB..
..BBBBBBBB..
..BCBBBBCB..
..BBBBBBBB..
...BBBBBB...
....BBBB....
.DDDDDDDDDD.
.D........D.
............
""")

    static let compile2: [[SpriteColor]] = parseSprite("""
....BBBB....
...BBBBBB...
..BBBBBBBB..
..BBEBBEBB..
..BBBBBBBB..
..BCBBBBCB..
..BBBBBBBB..
...BBBBBB...
....BBBB....
.DDDDDDDDDD.
.DGG......D.
............
""")

    static let compile3: [[SpriteColor]] = parseSprite("""
....BBBB....
...BBBBBB...
..BBBBBBBB..
..BBEBBEBB..
..BBBBBBBB..
..BCBBBBCB..
..BBBBBBBB..
...BBBBBB...
....BBBB....
.DDDDDDDDDD.
.DGGGG....D.
............
""")

    static let compile4: [[SpriteColor]] = parseSprite("""
....BBBB....
...BBBBBB...
..BBBBBBBB..
..BBEBBEBB..
..BBBBBBBB..
..BCBBBBCB..
..BBBBBBBB..
...BBBBBB...
....BBBB....
.DDDDDDDDDD.
.DGGGGGG..D.
............
""")

    static let compile5: [[SpriteColor]] = parseSprite("""
....BBBB....
...BBBBBB...
..BBBBBBBB..
..BBEBBEBB..
..BBBBBBBB..
..BCBBBBCB..
..BBBBBBBB..
...BBBBBB...
....BBBB....
.DDDDDDDDDD.
.DGGGGGGGGD.
............
""")

    static let compile6: [[SpriteColor]] = parseSprite("""
....BBBB....
...BBBBBB...
..BBBBBBBB..
..BBEBBEBB..
..BBBBBBBB..
..BCBMMBCB..
..BBBBBBBB..
...BBBBBB...
....BBBB....
.LLLLLLLLLL.
.LGGGGGGGGL.
............
""")

    // MARK: - Frame sequences for each animation

    static func frames(for animation: PetAnimation) -> [[[SpriteColor]]] {
        switch animation {
        case .idle:      return [idle1, idle2]
        case .happy:     return [happy1, happy2, happy3, happy2]
        case .tired:     return [tired1, tired2]
        case .sleeping:  return [sleeping1, sleeping2]
        case .excited:   return [excited1, excited2, excited3, excited2]
        case .critical:  return [critical1, critical2]
        case .reborn:    return [reborn1, reborn2, reborn3, reborn2]
        case .talking:   return [happy1, happy2]
        case .peeking:   return [peeking1, peeking2]
        case .falling:   return [falling1]
        case .squash:    return [squash1]
        case .leanLeft:  return [leanLeft1]
        case .leanRight: return [leanRight1]
        case .coding:    return [coding1, coding2, coding3, coding4, coding5, coding6, coding7, coding8]
        case .debugging: return [debug1, debug2, debug3, debug4, debug3, debug5]
        case .compiling: return [compile1, compile2, compile3, compile4, compile5, compile6]
        }
    }

    /// Frame duration in seconds for each animation type.
    static func frameDuration(for animation: PetAnimation) -> Double {
        switch animation {
        case .idle:      return 0.8
        case .happy:     return 0.3
        case .tired:     return 1.2
        case .sleeping:  return 1.0
        case .excited:   return 0.2
        case .critical:  return 1.5
        case .reborn:    return 0.25
        case .talking:   return 0.4
        case .peeking:   return 0.7
        case .falling, .squash, .leanLeft, .leanRight: return 0.5
        case .coding:    return 0.3
        case .debugging: return 0.35
        case .compiling: return 0.45
        }
    }
}
