// MARK: - Sprout sprite data (tiny plant in a pot)

/// All sprite frames for Sprout the plant.
/// Uses B=body (green), D=dark green, A=pot (terracotta), G=darker leaf, L=flower, E=eyes, W=white.
enum SproutSprites {

    // ── Idle frames (gentle sway) ──────────────────────────────────
    //  Plant: pot at bottom, stem, two leaves, face on the leaves/stem area

    static let idle1: [[SpriteColor]] = parseSprite("""
.....BB.....
....BBBB....
...BB..BB...
..BB....BB..
..GB....BG..
...BBEEBB...
....BBBB....
...AAAAAA...
..AAAAAAAA..
..AAAAAAAA..
..ADDDDDA...
...AAAAAA...
""")

    static let idle2: [[SpriteColor]] = parseSprite("""
............
.....BB.....
....BBBB....
...BB..BB...
..BB....BB..
..GB....BG..
...BBEEBB...
....BBBB....
...AAAAAA...
..AAAAAAAA..
..AAAAAAAA..
...AAAAAA...
""")

    // ── Happy frames (leaves flutter, little flower) ───────────────

    static let happy1: [[SpriteColor]] = parseSprite("""
.S...LL...S.
....LBBL....
...BB..BB...
..BB....BB..
..GB....BG..
...BBEEBB...
...BCMMCB...
...AAAAAA...
..AAAAAAAA..
..AAAAAAAA..
..ADDDDDA...
...AAAAAA...
""")

    static let happy2: [[SpriteColor]] = parseSprite("""
....S..S....
.S..LBBL..S.
...BB..BB...
.BB......BB.
.GB......BG.
...BBEEBB...
...BCMMCB...
...AAAAAA...
..AAAAAAAA..
..AAAAAAAA..
..ADDDDDA...
...AAAAAA...
""")

    static let happy3: [[SpriteColor]] = parseSprite("""
S....LL....S
....LBBL....
..BB....BB..
.BB......BB.
.GB......BG.
...BBEEBB...
...BCMMCB...
...AAAAAA...
..AAAAAAAA..
..AAAAAAAA..
..ADDDDDA...
...AAAAAA...
""")

    // ── Tired frames (drooping leaves) ─────────────────────────────

    static let tired1: [[SpriteColor]] = parseSprite("""
............
............
.....BB.....
....BBBB....
...BBBBBB...
..GBBEEBG...
...BBBBBB...
....BBBB....
...AAAAAA...
..AAAAAAAA..
..AAAAAAAA..
...AAAAAA...
""")

    static let tired2: [[SpriteColor]] = parseSprite("""
............
............
.....BB.....
....BBBB....
...BBBBBB...
..GBBDEBG...
...BBBBBB...
....BBBB....
...AAAAAA...
..AAAAAAAA..
..AAAAAAAA..
...AAAAAA...
""")

    // ── Sleeping frames (closed up, ZZZ) ───────────────────────────

    static let sleeping1: [[SpriteColor]] = parseSprite("""
..........Z.
.........Z..
.....BB.....
....BBBB....
...BBBBBB...
..GBDBBDBG..
...BBBBBB...
....BBBB....
...AAAAAA...
..AAAAAAAA..
..AAAAAAAA..
...AAAAAA...
""")

    static let sleeping2: [[SpriteColor]] = parseSprite("""
.........Z..
..........Z.
.....BB.....
....BBBB....
...BBBBBB...
..GBDBBDBG..
...BBBBBB...
....BBBB....
...AAAAAA...
..AAAAAAAA..
..AAAAAAAA..
...AAAAAA...
""")

    // ── Excited frames (bouncing bloom) ────────────────────────────

    static let excited1: [[SpriteColor]] = parseSprite("""
.S..LLLL..S.
...LBBBL....
..BB....BB..
.BB......BB.
.GB......BG.
...BBEEBB...
...BCMMCB...
...AAAAAA...
..AAAAAAAA..
..AAAAAAAA..
..ADDDDDA...
...AAAAAA...
""")

    static let excited2: [[SpriteColor]] = parseSprite("""
............
............
.S..LLLL..S.
...LBBBBL...
..BB....BB..
.GB.BEEB.BG.
...BCMMCB...
....BBBB....
...AAAAAA...
..AAAAAAAA..
..AAAAAAAA..
...AAAAAA...
""")

    static let excited3: [[SpriteColor]] = parseSprite("""
S...LLLL...S
.S.LBBBBL.S.
..BB....BB..
.BB......BB.
.GB......BG.
...BBEEBB...
...BCMMCB...
...AAAAAA...
..AAAAAAAA..
..AAAAAAAA..
..ADDDDDA...
...AAAAAA...
""")

    // ── Critical frames (wilting) ──────────────────────────────────

    static let critical1: [[SpriteColor]] = parseSprite("""
............
............
............
.....BB.....
....BBBB....
...BBEEBB...
...BBBBBB...
...BBBBBB...
....BBBB....
..AAAAAAAA..
..AAAAAAAA..
...AAAAAA...
""")

    static let critical2: [[SpriteColor]] = parseSprite("""
............
............
............
............
.....BB.....
...BBEEBB...
...BBBBBB...
...BBBBBB...
....BBBB....
.AAAAAAAAAA.
.AAAAAAAAAA.
..AAAAAAAA..
""")

    // ── Reborn frames (blooming explosion) ─────────────────────────

    static let reborn1: [[SpriteColor]] = parseSprite("""
S...LLLL...S
...LBBBBL...
..BB....BB..
.BB......BB.
.GB......BG.
...BBEEBB...
...BCMMCB...
...AAAAAA...
..AAAAAAAA..
..AAAAAAAA..
..ADDDDDA...
...AAAAAA...
""")

    static let reborn2: [[SpriteColor]] = parseSprite("""
.S.S.LL.S.S.
S..LLBBLL..S
..BB....BB..
.BB......BB.
.GB......BG.
...BBEEBB...
...BCMMCB...
...AAAAAA...
..AAAAAAAA..
..AAAAAAAA..
..ADDDDDA...
...AAAAAA...
""")

    static let reborn3: [[SpriteColor]] = parseSprite("""
S.S.SLLS.S.S
.S.SLLLLSS.S
S..LLBBLL..S
..BB....BB..
.BB......BB.
.GB.BEEB.BG.
...BCMMCB...
...AAAAAA...
..AAAAAAAA..
..AAAAAAAA..
..ADDDDDA...
...AAAAAA...
""")

    // ── Peeking frames (just pot and eyes peeking) ─────────────────

    static let peeking1: [[SpriteColor]] = parseSprite("""
............
............
............
............
............
............
............
............
.....BB.....
...BBEEBB...
...AAAAAA...
..AAAAAAAA..
""")

    static let peeking2: [[SpriteColor]] = parseSprite("""
............
............
............
............
............
............
.....BB.....
....BBBB....
...BBEEBB...
...BBBBBB...
...AAAAAA...
..AAAAAAAA..
""")

    // ── Movement poses ─────────────────────────────────────────────

    /// Falling: leaves flapping upward, pot tilting, surprised eyes
    static let falling1: [[SpriteColor]] = parseSprite("""
..BB....BB..
.GB....BBGB.
...BB..BB...
....BBBB....
...BWBBWB...
...BBEEBB...
....BBBB....
...AAAAAA...
..AAAAAAAA..
..AAAAAAAA..
..ADDDDDA...
...AAAAAA...
""")

    /// Squash: pot spread flat, leaves drooped to sides
    static let squash1: [[SpriteColor]] = parseSprite("""
............
............
............
............
............
............
.GB..BB..BG.
...BBEEBB...
..AAAAAAAA..
.AAAAAAAAAA.
.AADDDDDDAA.
.AAAAAAAAAA.
""")

    /// Lean left: plant tilted left, leaves trail right
    static let leanLeft1: [[SpriteColor]] = parseSprite("""
...BB.......
..BBBB......
.BB..BB.....
GB....BB....
.BBEEBB.....
..BBBB......
.AAAAAA.....
AAAAAAAA....
AAAAAAAA....
ADDDDDA.....
.AAAAAA.....
............
""")

    /// Lean right: plant tilted right, leaves trail left
    static let leanRight1: [[SpriteColor]] = parseSprite("""
.......BB...
......BBBB..
.....BB..BB.
....BB....BG
.....BBEEBB.
......BBBB..
.....AAAAAA.
....AAAAAAAA
....AAAAAAAA
.....ADDDDDA
.....AAAAAA.
............
""")

    // ── Coding frames (laptop slides out of pot) ─────────────────────

    static let coding1: [[SpriteColor]] = parseSprite("""
.....BB.....
....BBBB....
...BB..BB...
..BB....BB..
..GB....BG..
...BBEEBB...
....BBBB....
...AAAAAA...
..AAAAAAAA..
..AAAAAAAA..
.DDDDDDDDDD.
.DDDDDDDDDD.
""")

    static let coding2: [[SpriteColor]] = parseSprite("""
.....BB.....
....BBBB....
...BB..BB...
..BB....BB..
..GB....BG..
...BBEEBB...
....BBBB....
...AAAAAA...
.DDDDDDDDDD.
.DGGGGGGGGD.
.DAAAAAAAAD.
............
""")

    static let coding3: [[SpriteColor]] = parseSprite("""
.....BB.....
....BBBB....
...BB..BB...
..BB....BB..
..GB....BG..
...BBEEBB...
....BBBB....
...AAAAAA...
.DDDDDDDDDD.
.DGLGGGGGGD.
.DAADAAADAD.
............
""")

    static let coding4: [[SpriteColor]] = parseSprite("""
.....BB.....
....BBBB....
...BB..BB...
..BB....BB..
..GB....BG..
...BBEEBB...
....BBBB....
...AAAAAA...
.DDDDDDDDDD.
.DGGGGGLGGD.
.DADADAADAD.
............
""")

    static let coding5: [[SpriteColor]] = parseSprite("""
.....BB.....
....BBBB....
...BB..BB...
..BB....BB..
..GB....BG..
...BBEEBB...
....BBBB....
...AAAAAA...
.DDDDDDDDDD.
.DGGGGGGGLD.
.DAADAAADAD.
............
""")

    static let coding6: [[SpriteColor]] = parseSprite("""
.....BB.....
....BBBB....
...BB..BB...
..BB....BB..
..GB....BG..
...BBEEBB...
....BBBB....
...AAAAAA...
.DDDDDDDDDD.
.DGLGGGGGGD.
.DAADAAADAD.
............
""")

    static let coding7: [[SpriteColor]] = parseSprite("""
.....BB.....
....BBBB....
...BB..BB...
..BB....BB..
..GB....BG..
...BBEEBB...
....BBBB....
...AAAAAA...
..AAAAAAAA..
.DDDDDDDDDD.
.DDDDDDDDDD.
.DAAAAAAAAD.
""")

    static let coding8: [[SpriteColor]] = parseSprite("""
.....BB.....
....BBBB....
...BB..BB...
..BB....BB..
..GB....BG..
...BBEEBB...
....BBBB....
...AAAAAA...
..AAAAAAAA..
..AAAAAAAA..
..ADDDDDA...
...AAAAAA...
""")

    // ── Debugging frames (magnifier held by leaf) ────────────────────

    static let debug1: [[SpriteColor]] = parseSprite("""
.....BB..DD.
....BBBBBDGD
...BB..BBBDD
..BB....BB..
..GB....BG..
...BBEEBB...
....BBBB....
...AAAAAA...
..AAAAAAAA..
..AAAAAAAA..
..ADDDDDA...
...AAAAAA...
""")

    static let debug2: [[SpriteColor]] = parseSprite("""
.....BB..DD.
....BBBBBDGD
...BB..BBBDD
..BB....BB..
..GB....BG..
...BBDEBB...
....BBBB....
...AAAAAA...
..AAAAAAAA..
..AAAAAAAA..
..ADDDDDA...
...AAAAAA...
""")

    static let debug3: [[SpriteColor]] = parseSprite("""
.....BB.....
....BBBBBDD.
...BB..BBBDG
..BB....BBBD
..GB....BG..
...BBEEBB...
....BBBB....
...AAAAAA...
..AAAAAAAA..
..AAAAAAAA..
..ADDDDDA...
...AAAAAA...
""")

    static let debug4: [[SpriteColor]] = parseSprite("""
.....BBS....
....BBBB.S..
...BB..BB...
..BB....BB..
..GB....BG..
...BBEEBB...
....BBBB....
...AAAAAA...
..AAAAAAAA..
..AAAAAAAA..
..ADDDDDA...
...AAAAAA...
""")

    static let debug5: [[SpriteColor]] = parseSprite("""
.....BB.....
....BBBB....
...BB..BB...
..BB....BB..
..GB....BG..
...BBEEBB...
....BBBB....
...AAAAAA...
..AAAAAAAA..
..AAAAAAAA..
..ADDDDDA...
...AAAAAA...
""")

    // ── Compiling frames (progress bar below pot) ────────────────────

    static let compile1: [[SpriteColor]] = parseSprite("""
.....BB.....
....BBBB....
...BB..BB...
..BB....BB..
..GB....BG..
...BBEEBB...
....BBBB....
...AAAAAA...
..AAAAAAAA..
..AAAAAAAA..
.DDDDDDDDDD.
.D........D.
""")

    static let compile2: [[SpriteColor]] = parseSprite("""
.....BB.....
....BBBB....
...BB..BB...
..BB....BB..
..GB....BG..
...BBEEBB...
....BBBB....
...AAAAAA...
..AAAAAAAA..
..AAAAAAAA..
.DDDDDDDDDD.
.DGG......D.
""")

    static let compile3: [[SpriteColor]] = parseSprite("""
.....BB.....
....BBBB....
...BB..BB...
..BB....BB..
..GB....BG..
...BBEEBB...
....BBBB....
...AAAAAA...
..AAAAAAAA..
..AAAAAAAA..
.DDDDDDDDDD.
.DGGGG....D.
""")

    static let compile4: [[SpriteColor]] = parseSprite("""
.....BB.....
....BBBB....
...BB..BB...
..BB....BB..
..GB....BG..
...BBEEBB...
....BBBB....
...AAAAAA...
..AAAAAAAA..
..AAAAAAAA..
.DDDDDDDDDD.
.DGGGGGG..D.
""")

    static let compile5: [[SpriteColor]] = parseSprite("""
.....BB.....
....BBBB....
...BB..BB...
..BB....BB..
..GB....BG..
...BBEEBB...
....BBBB....
...AAAAAA...
..AAAAAAAA..
..AAAAAAAA..
.DDDDDDDDDD.
.DGGGGGGGGD.
""")

    static let compile6: [[SpriteColor]] = parseSprite("""
.....BB.....
....LBBL....
...BB..BB...
..BB....BB..
..GB....BG..
...BBMMBB...
....BBBB....
...AAAAAA...
..AAAAAAAA..
..AAAAAAAA..
.LLLLLLLLLL.
.LGGGGGGGGL.
""")

    // MARK: - Frame sequences

    static func frames(for animation: PetAnimation) -> [[[SpriteColor]]] {
        switch animation {
        case .idle:      return [idle1, idle2]
        case .happy:     return [happy1, happy2, happy3, happy2]
        case .tired:     return [tired1, tired2]
        case .sleeping:  return [sleeping1, sleeping2]
        case .excited:   return [excited1, excited2, excited3, excited2]
        case .critical:  return [critical1, critical2]
        case .reborn:    return [reborn1, reborn2, reborn3, reborn2]
        case .talking:   return [happy1, happy2]
        case .peeking:   return [peeking1, peeking2]
        case .falling:   return [falling1]
        case .squash:    return [squash1]
        case .leanLeft:  return [leanLeft1]
        case .leanRight: return [leanRight1]
        case .coding:    return [coding1, coding2, coding3, coding4, coding5, coding6, coding7, coding8]
        case .debugging: return [debug1, debug2, debug3, debug4, debug3, debug5]
        case .compiling: return [compile1, compile2, compile3, compile4, compile5, compile6]
        }
    }

    static func frameDuration(for animation: PetAnimation) -> Double {
        switch animation {
        case .idle:      return 0.9
        case .happy:     return 0.35
        case .tired:     return 1.3
        case .sleeping:  return 1.1
        case .excited:   return 0.22
        case .critical:  return 1.6
        case .reborn:    return 0.25
        case .talking:   return 0.4
        case .peeking:   return 0.8
        case .falling, .squash, .leanLeft, .leanRight: return 0.5
        case .coding:    return 0.3
        case .debugging: return 0.35
        case .compiling: return 0.45
        }
    }
}
